### PR TITLE
Added Trigrams line graph for Y

### PR DESCRIPTION
**Pull request by imbishal7**
Updated the code to make line graphs on tri-grams for yearly trends.

### CODE REVIEW

**Comment by PetrKorab** [comment]
@imbishal7 Thanks, very interesting. What is the use case for this improvement?

**Comment by imbishal7** [comment]
@PetrKorab I think combination of more words would be better, as a phrase is likely to be seen. I had to use it for my own work, so thought of updating it.

**Comment by PetrKorab** [comment]
@imbishal7 Arabica is now in the publishing process, but this is interesting. I need time to get tot this, but I will definitely add you as a contributor to this project.

**Comment by imbishal7** [comment]
@PetrKorab Alright, let me know if there is any issue. I am also planning to add parameters that lets users to get figure of desired size. It was quite difficult with the current one.

**Comment by PetrKorab** [comment]
I love the ideas. You can make further pull requests, I will add my revisions and make a new release. Thanks.

**Comment by PetrKorab** [comment]
If you make further updates, I am happy to add you as a co-developer of the library.

**Pull request merged**
